version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - S:/DOCKER-VOLUME/ZOOKEEPER-DATA:/var/lib/zookeeper/data
    networks:
      - internal
      
  kafka:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - S:/DOCKER-VOLUME/KAFKA-LOGS:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - internal 

      
networks:
  internal:
    external: true
