server:
  port: 4004

auth:
  service:
    url: http://localhost:4005

spring:
  cloud:
    gateway:
      routes:
# Routes for /api/auth/** to auth-Service
        - id: auth-service-route
          uri: http://localhost:4005
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

# Routes for /api/patient/** to Patient-Service
        - id: patient-service-routes
#          uri: http://patient-service:4001
          uri: http://localhost:4001
          predicates:
            - Path=/api/patient/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: api-docs-patient-routes
          uri: http://localhost:4001
          predicates:
            - Path=/api-docs/patients
          filters:
                - RewritePath=/api-docs/patients,/v3/api-docs



