server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service-routes
              uri: http://localhost:4001
              predicates:
                - path=/api/patient/**
              filters:
                - strip-prefix=1

            - id: api-docs-patient-routes
              uri: http://localhost:4001
              predicates:
                - path=/api-docs/patients
              filters:
                - rewrite-path=/api-docs/patients,/v3/api-docs



